"""onetomany

Revision ID: 5bf34ef3bcd3
Revises: 3dfcb1a201c3
Create Date: 2024-10-11 18:28:05.677883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bf34ef3bcd3'
down_revision = '3dfcb1a201c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('poster_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('poster_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
